artifacts_root: artifacts ## Path to store artifacts generated during the training process from the model

data_ingestion:
  root_dir: artifacts/data_ingestion ## Path to store the data
  source_URL: https://github.com/ankitghai83/branching_data/raw/refs/heads/main/samsum-test.7z
  local_data_file: artifacts/data_ingestion/data.7z
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation ## Path to store the data
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train","test","validation"]


data_transformation:
  root_dir: artifacts/data_transformation ## Path to store the data
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail


model_trainer:
  root_dir: artifacts/model_trainer ## Path to store the data
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail


model_evaluation:
  root_dir: artifacts/model_evaluation ## Path to store the data
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
